/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const GET_USER_GROUPS_REQUEST = 'GET_USER_GROUPS_REQUEST';
export const GET_USER_GROUPS_SUCCESS = 'GET_USER_GROUPS_SUCCESS';
export const GET_USER_GROUPS_FAILURE = 'GET_USER_GROUPS_FAILURE';
export const GET_GROUP_USERS_REQUEST = 'GET_GROUP_USERS_REQUEST';
export const GET_GROUP_USERS_SUCCESS = 'GET_GROUP_USERS_SUCCESS';
export const GET_GROUP_USERS_FAILURE = 'GET_GROUP_USERS_FAILURE';
export const CREATE_USER_GROUP_REQUEST = 'CREATE_USER_GROUP_REQUEST';
export const CREATE_USER_GROUP_SUCCESS = 'CREATE_USER_GROUP_SUCCESS';
export const CREATE_USER_GROUP_FAILURE = 'CREATE_USER_GROUP_FAILURE';
export const REMOVE_USER_GROUPS_REQUEST = 'REMOVE_USER_GROUPS_REQUEST';
export const REMOVE_USER_GROUPS_SUCCESS = 'REMOVE_USER_GROUPS_SUCCESS';
export const REMOVE_USER_GROUPS_FAILURE = 'REMOVE_USER_GROUPS_FAILURE';
export const GET_USERS_LIST_REQUEST = 'GET_USERS_LIST_REQUEST';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const GET_USERS_LIST_FAILURE = 'GET_USERS_LIST_FAILURE';
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const REMOVE_USERS_REQUEST = 'REMOVE_USERS_REQUEST';
export const REMOVE_USERS_SUCCESS = 'REMOVE_USERS_SUCCESS';
export const REMOVE_USERS_FAILURE = 'REMOVE_USERS_FAILURE';
export const ASSIGN_USERS_REQUEST = 'ASSIGN_USERS_REQUEST';
export const ASSIGN_USERS_SUCCESS = 'ASSIGN_USERS_SUCCESS';
export const ASSIGN_USERS_FAILURE = 'ASSIGN_USERS_FAILURE';
export const UNASSIGN_USERS_REQUEST = 'UNASSIGN_USERS_REQUEST';
export const UNASSIGN_USERS_SUCCESS = 'UNASSIGN_USERS_SUCCESS';
export const UNASSIGN_USERS_FAILURE = 'UNASSIGN_USERS_FAILURE';

